import { ArticleItem, EventItem, ShippedProduct, ExperienceItem, AwardItem, CoreStat } from '../types';
import qwertiaiImg from '../assets/images/qwertiai_banner_1787889265459.jpg';
import btcdImg from '../assets/images/btcd_banner_1787889342840.jpg';
import methImg from '../assets/images/meth_banner_1787889434930.jpg';
import mantleRwaImg from '../assets/images/mantle_rwa_banner_1787889538869.jpg';
import mantleAtlasImg from '../assets/images/mantle_atlas_banner_1787889625893.jpg';
import aiLensImg from '../assets/images/ai_lens_banner_1787889686394.jpg';
import bobOriginalImg from '../assets/images/bob_original.jpg';
import meteoraOriginalImg from '../assets/images/meteora_original.jpg';
import chatOriginalImg from '../assets/images/chat_original.jpg';

export const PERSONAL_INFO = {
  name: 'PinnacleCrypt',
  handle: '@PinnacleCrypt',
  tagline: 'I CREATE. I ORGANIZE. I SHIP.',
  subtagline: 'Content Creator • Event Organization & Management • Shipped Products',
  vibeQuote: 'Everything moves, but nothing screams.',
  bio: 'I write clear research on Web3 and AI, organize tech conferences and hackathons for growing developer communities, and build real digital products from scratch.',
  location: 'Remote',
  email: 'pinnaclecrypt@gmail.com',
  links: {
    x: 'https://x.com/PinnacleCrypt',
    telegram: 'https://t.me/PinnacleCrypt',
    github: 'https://github.com/PinnacleCryptNG',
    medium: 'https://medium.com/@Pinnacle_TheEnchanter',
    devto: 'https://dev.to/pinnaclecrypt',
    prompted: 'https://www.prmpted.com/pinnacle',
  },
  skills: [
    'Modular Architectures',
    'Zero-Knowledge Proofs',
    'AppChains & Rollups',
    'Solana SVM & Devnet',
    'Mantle Ecosystem',
    'Autonomous AI Agents',
    'DeFi Culture & Liquidity',
    'Technical Storytelling',
    'Grassroots Community Growth',
    'Prompt Engineering',
  ],
};

export const CORE_STATS: CoreStat[] = [
  {
    value: 8270,
    suffix: '+',
    label: 'Total Event Reach',
    sublabel: 'Across major tech & blockchain conferences',
  },
  {
    value: 150,
    suffix: '+',
    label: 'On-Chain Wallets Minted',
    sublabel: 'Grassroots Web3 onboarding in Nigeria',
  },
  {
    value: 4,
    suffix: '',
    label: 'Flagship AI/Web3 Products',
    sublabel: 'Conceived, prototyped & shipped live',
  },
  {
    value: 50,
    suffix: '+',
    label: 'Technical Essays & Threads',
    sublabel: 'Translating cutting-edge cryptography',
  },
];

export const VIBECODING_STEPS = [
  {
    step: '01',
    title: 'Idea',
    description: 'Deconstruct complex user friction into sharp mental models and architectural clarity.',
    accent: 'border-zinc-700 text-zinc-400',
  },
  {
    step: '02',
    title: 'Prompt',
    description: 'Frame precise multi-modal intent, system prompts, and deterministic schema specs.',
    accent: 'border-zinc-700 text-zinc-300',
  },
  {
    step: '03',
    title: 'Prototype',
    description: 'Fast-cycle reactive loops in modern TypeScript, AI context buffers, and chain devnets.',
    accent: 'border-[#7C3AED]/40 text-[#7C3AED]',
  },
  {
    step: '04',
    title: 'Iterate',
    description: 'Stress-test UX latency, feedback loops, real-world edge cases, and on-chain state.',
    accent: 'border-purple-500/50 text-purple-300',
  },
  {
    step: '05',
    title: 'Deploy',
    description: 'Ship production binaries to edge CDNs, smart contract registries, and live users.',
    accent: 'border-violet-400 text-white',
  },
];

export const ARTICLES_DATA: ArticleItem[] = [
  {
    id: 'art-m1',
    title: 'BOB: Building the Financial Layer Bitcoin Has Always Needed',
    subtitle: 'Bitcoin is often spoken about like it has already reached its final form.',
    excerpt: 'Bitcoin is often spoken about like it has already reached its final form. An in-depth analysis of BOB (Build On Bitcoin), hybrid L2 execution, native Bitcoin security, and how to unlock the trillion-dollar Bitcoin economy through expressive DeFi.',
    url: 'https://medium.com/@Pinnacle_TheEnchanter/bob-building-the-financial-layer-bitcoin-has-always-needed-d09d6264c886',
    date: 'MEDIUM ESSAY',
    readTime: '7 MIN READ',
    category: 'Bitcoin & DeFi',
    categories: ['Bitcoin', 'DeFi', 'Medium'],
    platform: 'medium',
    platformPublication: 'Medium / @Pinnacle_TheEnchanter',
    image: bobOriginalImg,
    coverGradient: 'from-amber-950/40 via-[#1F140A] to-[#0A0D14]',
    coverPattern: 'bitcoin-defi',
    tags: ['BOB', 'Bitcoin Layer 2', 'EVM Compatibility', 'Bitcoin DeFi'],
    metrics: {
      claps: '1.2K',
      views: '3.8K',
      bookmarks: '210',
    },
  },
  {
    id: 'art-1',
    title: 'QwertiAI: The Layer that finally makes Defi make Sense',
    subtitle: 'QwertiAI does not assume users need more tools. It assumes they need less responsibility over the complexity those tools create.',
    excerpt: 'QwertiAI does not assume users need more tools. It assumes they need less responsibility over the complexity those tools create.',
    url: 'https://x.com/PinnacleCrypt/status/2039607960888860974',
    date: 'FEB 2025',
    readTime: '6 MIN READ',
    category: 'AI & DeFi',
    categories: ['AI', 'DeFi'],
    platform: 'x',
    image: qwertiaiImg,
    coverGradient: 'from-blue-950/40 via-[#0B1A2C] to-[#0A0D14]',
    coverPattern: 'ai-defi',
    metrics: {
      views: '18.4K',
      likes: '420',
      retweets: '86',
      bookmarks: '135',
    },
  },
  {
    id: 'art-m2',
    title: "Exploring Meteora DLMM: Solana's Revolutionary Dynamic Liquidity Protocol",
    subtitle: 'Meteora DLMM: Dynamic Liquidity Market Maker on Solana',
    excerpt: 'Exploring Meteora DLMM on Solana: Dynamic liquidity market making, customized bin distribution, zero-slippage trading mechanics, and how dynamic fee curves protect liquidity providers during volatile price discovery.',
    url: 'https://medium.com/@Pinnacle_TheEnchanter/exploring-meteora-dlmm-solanas-revolutionary-dynamic-liquidity-protocol-d78b9c3df1b4',
    date: 'MEDIUM ESSAY',
    readTime: '8 MIN READ',
    category: 'Solana & DeFi',
    categories: ['Solana', 'DeFi', 'Medium'],
    platform: 'medium',
    platformPublication: 'Medium / @Pinnacle_TheEnchanter',
    image: meteoraOriginalImg,
    coverGradient: 'from-orange-950/40 via-[#1C0D0A] to-[#0A0D14]',
    coverPattern: 'solana-dlmm',
    tags: ['Meteora', 'DLMM', 'Solana DeFi', 'Liquidity Pools', 'AMM Mechanics'],
    metrics: {
      claps: '950',
      views: '2.9K',
      bookmarks: '180',
    },
  },
  {
    id: 'art-2',
    title: 'Yield that does not depend on the weather',
    subtitle: 'BTCD\'s sBTCD primitive generates return from productive collateral and volatility - not from perpetual funding staying polite.',
    excerpt: 'BTCD\'s sBTCD primitive generates return from productive collateral and volatility - not from perpetual funding staying polite.',
    url: 'https://x.com/PinnacleCrypt/status/2057506105803108655',
    date: 'JAN 2025',
    readTime: '5 MIN READ',
    category: 'Yield',
    categories: ['Yield'],
    platform: 'x',
    image: btcdImg,
    coverGradient: 'from-indigo-950/40 via-[#0F1426] to-[#0A0D14]',
    coverPattern: 'yield',
    metrics: {
      views: '12.8K',
      likes: '310',
      retweets: '54',
      bookmarks: '92',
    },
  },
  {
    id: 'art-m3',
    title: 'Chat: The Gateway to Web 3.0',
    subtitle: 'Decentralized messaging, social graph aggregation, and conversational UX bridging everyday users into Web3.',
    excerpt: 'Chat is humanity\'s most natural communication interface. Examining how decentralized chat protocols, conversational wallets, and social layers serve as the frictionless gateway onboarding the next billion users into Web 3.0.',
    url: 'https://medium.com/@Pinnacle_TheEnchanter/chat-the-gateway-to-web-3-0-1c174be7fd24',
    date: 'MEDIUM ESSAY',
    readTime: '6 MIN READ',
    category: 'Web3 UX & Social',
    categories: ['Web3 UX', 'Messaging', 'Medium'],
    platform: 'medium',
    platformPublication: 'Medium / @Pinnacle_TheEnchanter',
    image: chatOriginalImg,
    coverGradient: 'from-blue-950/40 via-[#0D182E] to-[#0A0D14]',
    coverPattern: 'web3-chat',
    tags: ['Web3 Messaging', 'Conversational UX', 'SocialFi', 'Onboarding'],
    metrics: {
      claps: '880',
      views: '2.4K',
      bookmarks: '145',
    },
  },
  {
    id: 'art-3',
    title: 'Staking that still lets the capital move',
    subtitle: 'mETH Protocol sits in a very specific place inside Ethereum: making ETH staking useful in everyday DeFi, without locking people out of their funds.',
    excerpt: 'mETH Protocol sits in a very specific place inside Ethereum: making ETH staking useful in everyday DeFi, without locking people out of their funds.',
    url: 'https://x.com/PinnacleCrypt/status/2063682861543125355',
    date: 'DEC 2024',
    readTime: '7 MIN READ',
    category: 'Staking',
    categories: ['Staking'],
    platform: 'x',
    image: methImg,
    coverGradient: 'from-blue-950/40 via-[#0D192C] to-[#0A0D14]',
    coverPattern: 'staking',
    metrics: {
      views: '15.2K',
      likes: '380',
      retweets: '72',
      bookmarks: '110',
    },
  },
  {
    id: 'art-4',
    title: "Tokenization's next chapter is utility",
    subtitle: 'An asset that simply exists on-chain is only half the story. Mantle is assembling the rails that let tokenized capital actually work.',
    excerpt: 'An asset that simply exists on-chain is only half the story. Mantle is assembling the rails that let tokenized capital actually work.',
    url: 'https://x.com/PinnacleCrypt/status/2072201818998800502',
    date: 'NOV 2024',
    readTime: '8 MIN READ',
    category: 'RWA Tokenization',
    categories: ['RWA Tokenization'],
    platform: 'x',
    image: mantleRwaImg,
    coverGradient: 'from-cyan-950/40 via-[#0B1E28] to-[#0A0D14]',
    coverPattern: 'rwa',
    metrics: {
      views: '22.1K',
      likes: '540',
      retweets: '118',
      bookmarks: '190',
    },
  },
  {
    id: 'art-5',
    title: 'Building AI people can actually trust',
    subtitle: 'Mantle Atlas does not answer first. It researches, organizes evidence, measures confidence, and is willing to say the data is not enough.',
    excerpt: 'Mantle Atlas does not answer first. It researches, organizes evidence, measures confidence, and is willing to say the data is not enough.',
    url: 'https://x.com/PinnacleCrypt/status/2072703500945969446',
    date: 'OCT 2024',
    readTime: '5 MIN READ',
    category: 'AI',
    categories: ['AI'],
    platform: 'x',
    image: mantleAtlasImg,
    coverGradient: 'from-blue-950/40 via-[#0D182A] to-[#0A0D14]',
    coverPattern: 'ai-atlas',
    metrics: {
      views: '16.7K',
      likes: '410',
      retweets: '89',
      bookmarks: '142',
    },
  },
  {
    id: 'art-6',
    title: 'AI as a lens, not an autopilot',
    subtitle: 'I did not need more speed. I needed clarity - a thinking partner that illuminates blind spots, then waits for a human veto.',
    excerpt: 'I did not need more speed. I needed clarity - a thinking partner that illuminates blind spots, then waits for a human veto.',
    url: 'https://x.com/PinnacleCrypt/status/2037097252808769887',
    date: 'SEP 2024',
    readTime: '4 MIN READ',
    category: 'AI',
    categories: ['AI'],
    platform: 'x',
    image: aiLensImg,
    coverGradient: 'from-blue-950/50 via-[#101C30] to-[#0A0D14]',
    coverPattern: 'superpower',
    metrics: {
      views: '19.8K',
      likes: '495',
      retweets: '104',
      bookmarks: '168',
    },
  },
];

const NOTION_EVENTS_PORTFOLIO_URL = 'https://plume-report-019.notion.site/Pinnacles-Proof-of-work-584a78210868837f9dcf01486eab0a81';

export const EVENTS_DATA: EventItem[] = [
  {
    id: 'ev-1',
    name: 'Web3 North Conference',
    edition: 'Flagship Edition',
    location: 'Kaduna',
    country: 'Nigeria',
    attendees: '5,000+ Attendees',
    role: 'Co-Anchor & Marketing Lead',
    date: 'July 12, 2025',
    image: '/Web3NorthCon.jpg',
    notionUrl: NOTION_EVENTS_PORTFOLIO_URL,
    highlight: 'Largest Web3 builder and developer gathering in Northern Nigeria',
    description: 'Spearheaded comprehensive digital marketing campaign, co-anchored the main stage for 5,000+ developers, creators, and investors, and received Medal of Recognition for exceptional contribution.',
    stats: [
      { label: 'Total In-Person Attendance', value: '5,000+' },
      { label: 'Ecosystem Partners', value: '24+' },
      { label: 'Keynote & Panel Sessions', value: '18' },
    ],
    tags: ['Keynote Hosting', 'Brand Marketing', 'Builder Ecosystem', 'PR & Media'],
    gradient: 'from-purple-900/40 via-neutral-900 to-black',
    accentColor: '#7C3AED',
  },
  {
    id: 'ev-2',
    name: 'ICP Blockchain Meetup',
    edition: 'Developer & Ecosystem Workshop',
    location: 'Kaduna',
    country: 'Nigeria',
    attendees: '700+ Attendees',
    walletsCreated: '50+ Wallets Created',
    role: 'Lead Host & Technical Facilitator',
    date: 'March 9, 2025',
    image: '/ICP.jpg',
    notionUrl: NOTION_EVENTS_PORTFOLIO_URL,
    highlight: 'Pioneered Internet Computer Protocol canisters & direct developer onboarding',
    description: 'Organized and hosted the premiere ICP ecosystem session in Kaduna, delivering technical overviews on smart canisters and directly facilitating on-chain onboarding for 50+ new developers across 4 universities.',
    stats: [
      { label: 'Participants', value: '700+' },
      { label: 'Wallets Onboarded', value: '50+' },
      { label: 'Live Canister Demos', value: '4' },
    ],
    tags: ['ICP', 'Canister Smart Contracts', 'Lead Host', 'Developer Onboarding'],
    gradient: 'from-indigo-950/40 via-neutral-900 to-black',
    accentColor: '#6366F1',
  },
  {
    id: 'ev-3',
    name: 'JUP in the North',
    edition: 'Jupiter Exchange Community Summit',
    location: 'Kaduna',
    country: 'Nigeria',
    attendees: '600+ Attendees',
    role: 'Keynote Panelist & Ecosystem Voice',
    date: 'February 8, 2025',
    image: '/JupInTheNorth.jpg',
    notionUrl: NOTION_EVENTS_PORTFOLIO_URL,
    highlight: 'Unpacking Solana DeFi primitives, routing, and Jupiter ecosystem expansion',
    description: 'Shared stage insights as a featured panelist on decentralized exchange aggregation, Solana liquidity routing, perpetual markets, and community-first governance models.',
    stats: [
      { label: 'Audience Reach', value: '600+' },
      { label: 'DeFi Discussion Panels', value: '2' },
      { label: 'Solana Swaps Demoed', value: '100+' },
    ],
    tags: ['Solana', 'Jupiter', 'DeFi Primitives', 'Panelist'],
    gradient: 'from-emerald-950/30 via-neutral-900 to-black',
    accentColor: '#10B981',
  },
  {
    id: 'ev-4',
    name: 'TON Community Tour',
    edition: '7-Part Regional Circuit',
    location: 'Kaduna & Environs',
    country: 'Nigeria',
    attendees: '1,750+ Cumulative Reach',
    walletsCreated: '100+ Wallets Created',
    role: 'Co-Anchor & Lead Publicity',
    date: 'April 27, 2025',
    image: '/TONTour.jpg',
    notionUrl: NOTION_EVENTS_PORTFOLIO_URL,
    highlight: '7-part grassroots tour bringing Telegram Mini Apps and TON to regional campuses',
    description: 'Executed an intensive 7-stop regional tour introducing student developers and creators to Telegram Web Apps, Tonkeeper wallets, Notcoin, Catizen, and lightweight smart contract development.',
    stats: [
      { label: 'Tour Stops Completed', value: '7 Parts' },
      { label: 'Cumulative Reach', value: '1,750+' },
      { label: 'Wallets Created', value: '100+' },
    ],
    tags: ['TON', 'Telegram Mini Apps', 'Grassroots Tour', 'Co-Anchor'],
    gradient: 'from-blue-950/40 via-neutral-900 to-black',
    accentColor: '#3B82F6',
  },
  {
    id: 'ev-5',
    name: 'Avalanche Game Night',
    edition: 'Team 1 Game Night – Avax Nigeria',
    location: 'Kaduna',
    country: 'Nigeria',
    attendees: '120+ Attendees',
    role: 'Co-Anchor & Head of Media',
    date: 'May 30, 2024',
    image: '/AvalancheGameNight.jpg',
    notionUrl: NOTION_EVENTS_PORTFOLIO_URL,
    highlight: 'Interactive gaming competition highlighting Avalanche Subnets & Web3 esports',
    description: 'Coordinated media coverage, dynamic live streaming, and interactive tournaments demonstrating top Avalanche Console Games (Off the Grid, Shatterline, Maple Story) powered by Avalanche subnet architecture.',
    stats: [
      { label: 'Active Gamers', value: '120+' },
      { label: 'Tournaments Run', value: '3' },
      { label: 'Media Impressions', value: '45K+' },
    ],
    tags: ['Avalanche', 'Web3 Gaming', 'Head of Media', 'Live Event'],
    gradient: 'from-red-950/30 via-neutral-900 to-black',
    accentColor: '#EF4444',
  },
  {
    id: 'ev-6',
    name: 'SonicLabs Developer Meetup',
    edition: 'EVM 10k TPS & Builder Workshop',
    location: 'Kaduna',
    country: 'Nigeria',
    attendees: '100+ Attendees',
    walletsCreated: '25+ HackQuest Sign-ups',
    role: 'Host & Event Coordinator',
    date: 'May 17, 2025',
    image: '/SonicLabs.jpg',
    notionUrl: NOTION_EVENTS_PORTFOLIO_URL,
    highlight: 'Exploring ultra-fast EVM execution, developer incentives and HackQuest courses',
    description: 'Hosted an intimate developer cohort focused on Sonic blockchain architecture, fee monetization mechanisms, and enrolled 25+ developers into specialized builder tracks with HackQuest.',
    stats: [
      { label: 'Engineers Present', value: '100+' },
      { label: 'Course Enrolments', value: '25+' },
      { label: 'Builder Grants Discussed', value: '3' },
    ],
    tags: ['SonicLabs', 'High-Speed EVM', 'Host', 'Dev Education'],
    gradient: 'from-amber-950/30 via-neutral-900 to-black',
    accentColor: '#F59E0B',
  },
];

export const PRODUCTS_DATA: ShippedProduct[] = [
  {
    id: 'prod-king-shezy',
    name: 'King Shezy Global Nig Ltd',
    tagline: 'Corporate Enterprise Landing Page & Brand Showcase',
    domain: 'king-shezy-global-nig-ltd.vercel.app/',
    description: 'A modern, high-trust corporate landing page built for King Shezy Global Nig Ltd.',
    extendedDescription: 'A sleek corporate digital presence showcasing the company’s multi-sector commercial ventures, global logistics, and partnership opportunities.',
    expected: 'A high-trust corporate landing page to establish the global business presence of King Shezy Global Nig Ltd, showcasing their core services, international trading portfolio, corporate values, and direct client inquiry channels.',
    built: 'I designed and built a fast, responsive company landing page with an executive hero presentation, clear service breakdowns, company profile highlights, interactive inquiry forms, and mobile-optimized layouts.',
    category: 'Corporate Landing Page',
    stack: ['CORPORATE LANDING PAGE', 'COMPANY CATALOGUE', 'NEXT.JS'],
    highlights: [
      'Executive corporate identity and service portfolio',
      'Interactive client inquiry and contact channels',
      'Mobile-optimized responsive architecture',
    ],
    links: [
      { label: 'Live', url: 'https://king-shezy-global-nig-ltd.vercel.app/', type: 'live' },
      { label: 'Live App', url: 'https://king-shezy-global-nig-ltd.vercel.app/', type: 'repo' },
    ],
    liveUrl: 'https://king-shezy-global-nig-ltd.vercel.app/',
    codeUrl: 'https://king-shezy-global-nig-ltd.vercel.app/',
    featured: true,
    status: 'LIVE CLIENT BUILD',
    year: '2026',
    date: '2026',
    badge: 'CLIENT BUILD',
    color: '#D8F965',
    coverGradient: 'from-amber-950/40 via-[#1C160E] to-[#0D0D0D]',
    coverPattern: 'kingshezy',
    projectType: 'client',
  },
  {
    id: 'prod-tailory',
    name: 'Tailory',
    tagline: 'Interactive Pet Keepsake & Storybook Platform',
    domain: 'tailory-ten.vercel.app/',
    description: 'A creative platform that turns pet milestones and photos into keepsake storybooks.',
    extendedDescription: 'A warm and interactive digital keepsake platform for pet owners and businesses to turn pet photos and life milestones into custom illustrated storybooks.',
    expected: 'A warm, interactive digital keepsake platform for pet owners and animal shelters to turn pet photos and life milestones into custom illustrated storybooks.',
    built: 'I built a responsive web application featuring custom story chapters, photo milestone albums, digital keepsake cards, and an interactive reader mode.',
    category: 'Creative Web App',
    stack: ['CREATIVE WEB APP', 'STORYBOOK CATALOGUE', 'NEXT.JS'],
    highlights: [
      'Interactive reader layout for digital pet keepsakes',
      'Milestone gallery and custom chapter generator',
      'High-resolution certificate export',
    ],
    links: [
      { label: 'Live', url: 'https://tailory-ten.vercel.app/', type: 'live' },
      { label: 'Live App', url: 'https://tailory-ten.vercel.app/', type: 'repo' },
    ],
    liveUrl: 'https://tailory-ten.vercel.app/',
    codeUrl: 'https://tailory-ten.vercel.app/',
    featured: true,
    status: 'LIVE DEMO',
    year: '2026',
    date: '2026',
    badge: 'LIVE DEMO',
    color: '#D8F965',
    coverGradient: 'from-amber-950/40 via-[#1C160E] to-[#0D0D0D]',
    coverPattern: 'tailory',
    projectType: 'hackathon',
  },
  {
    id: 'prod-memory',
    name: 'Memory',
    tagline: 'Intelligent Notes & Personal Workspace Assistant',
    domain: 'ai-memory-alpha.vercel.app/',
    description: 'A distraction-free workspace that helps people organize thoughts and find notes instantly.',
    extendedDescription: 'An intuitive workspace app with instant note search, categorized notebooks, daily task summaries, and a dark-mode conversational view.',
    expected: 'A distraction-free personal assistant for busy professionals to organize quick thoughts, track daily tasks, and easily search past notes without clutter.',
    built: 'I developed an intuitive workspace app with instant note search, categorized notebooks, daily task summaries, and a modern conversational view.',
    category: 'Productivity App',
    stack: ['PRODUCTIVITY APP', 'WORKSPACE CATALOGUE', 'NEXT.JS'],
    highlights: [
      'Instant search across all personal notes and ideas',
      'Distraction-free markdown workspace with category tags',
      'Fast responsive dark mode interface',
    ],
    links: [
      { label: 'Live', url: 'https://ai-memory-alpha.vercel.app/', type: 'live' },
      { label: 'Live App', url: 'https://ai-memory-alpha.vercel.app/', type: 'repo' },
    ],
    liveUrl: 'https://ai-memory-alpha.vercel.app/',
    codeUrl: 'https://ai-memory-alpha.vercel.app/',
    featured: true,
    status: 'LIVE DEMO',
    year: '2026',
    date: '2026',
    badge: 'LIVE DEMO',
    color: '#D8F965',
    coverGradient: 'from-violet-950/40 via-[#141122] to-[#0D0D0D]',
    coverPattern: 'memory',
    projectType: 'hackathon',
  },
  {
    id: 'prod-margin',
    name: 'Margin',
    tagline: 'Interactive Financial Dashboard & Risk Simulator',
    domain: 'margin-jade-alpha.vercel.app/',
    description: 'A live risk calculator and finance simulator built for hackathon competition.',
    extendedDescription: 'An interactive finance dashboard with live slider simulations, responsive health visualizers, and clear collateral management tools.',
    expected: 'A modern financial calculator and visual simulator built for a hackathon to help users test loan safety and manage trading risk in real time.',
    built: 'I created an interactive finance dashboard with live slider simulations, responsive health visualizers, and clear position management tools.',
    category: 'Finance Platform',
    stack: ['FINANCE PLATFORM', 'DASHBOARD CATALOGUE', 'NEXT.JS'],
    highlights: [
      'Real-time interactive position health sliders',
      'Instant liquidation and risk projection visualizers',
      'Hackathon finalist submission with responsive mobile views',
    ],
    links: [
      { label: 'Live', url: 'https://margin-jade-alpha.vercel.app/', type: 'live' },
      { label: 'Live App', url: 'https://margin-jade-alpha.vercel.app/', type: 'repo' },
    ],
    liveUrl: 'https://margin-jade-alpha.vercel.app/',
    codeUrl: 'https://margin-jade-alpha.vercel.app/',
    featured: true,
    status: 'LIVE DEMO',
    year: '2025',
    date: '2025',
    badge: 'LIVE DEMO',
    color: '#D8F965',
    coverGradient: 'from-emerald-950/40 via-[#0E1A14] to-[#0D0D0D]',
    coverPattern: 'margin',
    projectType: 'hackathon',
  },
  {
    id: 'prod-mantle-atlas',
    name: 'Mantle Atlas',
    tagline: 'Ecosystem Discovery & Live Metrics Directory',
    domain: 'mantle-ask.vercel.app/',
    description: 'A fast project directory and analytics hub for exploring community projects.',
    extendedDescription: 'A fast project directory with instant search, category filters, real-time metric cards, and clean visual summaries.',
    expected: 'A clean search directory for exploring community projects, builder grants, and verified live stats without getting lost in complex spreadsheets.',
    built: 'I developed a fast project directory with instant search, category filters, real-time metric cards, and clean visual summaries.',
    category: 'Community Portal',
    stack: ['COMMUNITY PORTAL', 'PROJECT CATALOGUE', 'NEXT.JS'],
    highlights: [
      'Instant search and filterable directory of ecosystem tools',
      'Real-time metric cards and grant verification badges',
      'Clean typography and lightweight client-side caching',
    ],
    links: [
      { label: 'Live', url: 'https://mantle-ask.vercel.app/', type: 'live' },
      { label: 'Live App', url: 'https://mantle-ask.vercel.app/', type: 'repo' },
    ],
    liveUrl: 'https://mantle-ask.vercel.app/',
    codeUrl: 'https://mantle-ask.vercel.app/',
    featured: true,
    status: 'LIVE DEMO',
    year: '2025',
    date: '2025',
    badge: 'LIVE DEMO',
    color: '#D8F965',
    coverGradient: 'from-cyan-950/40 via-[#0E181D] to-[#0D0D0D]',
    coverPattern: 'mantle-atlas',
    projectType: 'hackathon',
  },
];

export const EXPERIENCES: ExperienceItem[] = [
  {
    period: '',
    role: 'Technical Writer & Research Analyst',
    organization: 'Technical Essays & Research Theses',
    location: 'Remote',
    summary: 'Writing clear, accessible research on Web3 protocols, AI models, and developer tooling for thousands of readers.',
    accomplishments: [
      'Published in-depth research breakdowns on decentralized finance and artificial intelligence.',
      'Authored technical guides and conceptual explainers on modular blockchains and developer frameworks.',
      'Helped thousands of active builders understand complex concepts through simple mental models.',
    ],
    tags: ['Technical Writing', 'Web3 Research', 'AI Theses', 'Content Strategy'],
  },
  {
    period: '',
    role: 'Product Builder & Developer',
    organization: 'Independent Products & Applications',
    location: 'Remote',
    summary: 'Designing and building responsive web applications, AI-powered tools, and smart contract interfaces from scratch.',
    accomplishments: [
      'Built and launched 4 live applications: Tailory, Memory, Margin, and Mantle Atlas.',
      'Integrated modern AI reasoning and on-chain querying into fast, user-friendly interfaces.',
      'Created open-source tools, hackathon projects, and developer prototypes.',
    ],
    tags: ['Product Development', 'Web Applications', 'TypeScript', 'AI Tooling'],
  },
  {
    period: '',
    role: 'Event Organizer & Community Lead',
    organization: 'Tech Conferences & Developer Summits',
    location: 'Remote & On-Site',
    summary: 'Organizing tech conferences, hackathons, and developer bootcamps that bring together thousands of attendees.',
    accomplishments: [
      'Organized and hosted major tech summits and developer conferences with thousands of participants.',
      'Led hands-on onboarding sessions, helping new builders set up wallets and ship their first projects.',
      'Collaborated with ecosystem partners and global tech foundations to support developer talent.',
    ],
    tags: ['Event Management', 'Tech Conferences', 'Hackathons', 'Community Growth'],
  },
];

export const AWARDS_DATA: AwardItem[] = [
  {
    id: 'award-1',
    title: 'Best Male Twitter Co-Host',
    issuer: 'CTNG (Crypto Twitter Nigeria)',
    year: '2023',
    category: 'Award',
    badge: 'CTNG AWARDS',
    highlight: 'Honored for exceptional technical moderation and space hosting',
    description: 'Voted Best Male Twitter Co-Host by the Nigerian crypto and Web3 community for hosting engaging, educational Twitter Spaces and elevating regional builder voices.',
    proofUrl: 'https://x.com/PinnacleCrypt/status/1741128379384905825',
  },
  {
    id: 'award-2',
    title: 'Certificate of Honor — Best PlayCrivia Twitter Space Host',
    issuer: 'PlayCrivia',
    year: '2024',
    category: 'Certificate',
    badge: 'CERTIFICATE OF HONOR',
    highlight: 'Recognized for high-energy web3 trivia and interactive hosting',
    description: 'Awarded Certificate of Honor for leading and moderating high-engagement interactive trivia sessions, community gamification, and Web3 education broadcasts.',
  },
  {
    id: 'award-3',
    title: 'Medal of Recognition',
    issuer: 'JupNG (Jupiter Nigeria Community)',
    year: '2025',
    category: 'Medal',
    badge: 'ECOSYSTEM MEDAL',
    highlight: 'Awarded for grassroots Solana DeFi education and leadership',
    description: 'Awarded an official medal of recognition by the Jupiter Nigeria community for driving Solana DeFi awareness, organizing ecosystem meetups, and onboarding new builders.',
    proofUrl: 'https://x.com/PinnacleCrypt/status/2006677113886196056',
  },
  {
    id: 'award-4',
    title: 'Award of Recognition — Best Content Creator',
    issuer: 'JupNG & Web3 Community Honors',
    year: '2025',
    category: 'Award',
    badge: 'BEST CONTENT CREATOR',
    highlight: 'Celebrated for high-impact research essays, viral threads & visual guides',
    description: 'Recognized as Best Content Creator for outstanding research contributions, Medium deep-dives, and educational visual breakdowns across decentralized finance and AI ecosystems.',
    proofUrl: 'https://x.com/PinnacleCrypt/status/2006677113886196056',
  },
  {
    id: 'award-5',
    title: '3-Time Research Grant Recipient',
    issuer: 'Axelar Network',
    year: '2024',
    category: 'Grant',
    badge: '3X RESEARCH GRANT',
    highlight: 'Awarded 3 consecutive technical grants for cross-chain interoperability research',
    description: 'Successfully awarded 3 technical research grants by Axelar Network for authoring comprehensive architectural analyses on General Message Passing (GMP), Cosmos-EVM bridging, and cross-chain liquidity networks.',
    proofUrl: 'https://x.com/PinnacleCrypt/status/1823680104305684781',
  },
];
